// Yujiang Li All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace LGamePlayTags
{
	/** Input Tags **/
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact)
}
