// Yujiang Li All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace LGamePlayTags
{
	/** Input Tags **/
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipDao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipDao);

	/** Player Tags **/
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Dao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Dao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Dao);
}
