// Yujiang Li All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace LGamePlayTags
{
	/** Input Tags **/
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipDao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipDao);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Dao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Dao);

	/** Player Tags **/
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Dao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Dao);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Dao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Dao);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Dao);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Dao);
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Dao);

	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	/** Enemy Tags **/
	ACTIONROGUELIKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
}
